# Generated by Django 5.0.7 on 2024-07-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='landscape',
            field=models.BooleanField(default=False),
        ),
    ]
